### PR TITLE
Add non-SFC components support

### LINKED ISSUE #1: Support non-SFC components
Migrated from https://github.com/pocka/storybook-addon-vue-info/issues/119

### PR DESCRIPTION
**Pull request by pocka**
## Related issues / Problem

> Add permalink to the issues related to this changes.
> You can also use [closing keyword](https://help.github.com/en/github/managing-your-work-on-github/closing-issues-using-keywords) to close the issue automatically.
>
> If there is no issues related to the problem, please describe it.

close #1 

## What I did

> Please write simple and concise description about the changes.

Add non-SFC support.

## Checklist

> Please check below.

- [x] Added one or more test
- [x] This PR does not includes any other changes that is unrelated to the problem/feature

### CODE REVIEW

**Comment by Aaron-Pool** [comment]
@pocka is there a reason that the `?component` query is still needed for non-SFC components? I thought that was originally because SFCs call the loader on a file several times as they parse different types of the component?

**Comment by pocka** [comment]
@Aaron-Pool 
Yes, to make sure the loader only applies to Vue component files. If there is no restriction (like `{ test: /\.js$/, loader: 'vue-docgen-loader' }`), every `.js` files will be parsed with vue-docgen-api and `__docgen` property will be added to the export when it succeeds. This increases build time and might break the js files.

**Comment by Aaron-Pool** [comment]
Ah, ok, so it's not so much the query parameter as it is having SOME way to distinguish between components and non components. So, theoretically if there was some other pattern, such as a naming convention, that could be used instead?

**Comment by pocka** [comment]
@Aaron-Pool 
Yeah, for example, I use `*.vue.js` rule in tests.
https://github.com/pocka/vue-docgen-loader/blob/master/test/compiler.js#L26

**Pull request merged**
